version: '3.5'
services:
  aif-demo:
    image: woohyeokchoi/aif-demo-project
    networks:
      - web-network
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      CALLBACK_URL: "https://keltpower0.kaist.ac.kr/apis/external/types/google-calendar/auth"
      CREDENTIAL_PATH: "/home/aif-demo/credentials.json"
    volumes:
      - "D:/Workspace/Projects/AIF-Demo-Project/credentials:/home/aif-demo"
    deploy:
      replicas: 1
      restart_policy: 
        delay: 5s
        max_attempts: 10
      placement:
        constraints:
          - node.role == manager
  proxy:
    image: woohyeokchoi/nginx-https
    ports:
      - "80:80"
      - "443:443"
      - "50051:50051"
    environment:
      SERVER_DOMAIN: "keltpower0.kaist.ac.kr"
      SERVER_EMAIL: "keltpower0@gmail.com"
      IS_DEBUG: "true"
    volumes:
      - "D:/Workspace/Projects/AIF-Demo-Project/conf:/home/conf/nginx"
    networks:
      - web-network
    deploy:
      replicas: 1
      restart_policy: 
        delay: 10s
        max_attempts: 10
      placement:
        constraints:
          - node.role == manager

networks:
  web-network:
    driver: overlay
    attachable: true


