# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: alarm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='alarm.proto',
  package='aif.kaist',
  syntax='proto3',
  serialized_options=_b('\n\026aif.kaist.iclab.protosB\013AlarmProtos'),
  serialized_pb=_b('\n\x0b\x61larm.proto\x12\taif.kaist\x1a\x1bgoogle/protobuf/empty.proto\"\xcf\x02\n\x05\x41larm\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08\x61larm_id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x65lay_millis\x18\x04 \x01(\x03\x12\x17\n\x0finterval_millis\x18\x05 \x01(\x03\x12\x18\n\x10scheduled_millis\x18\x06 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\x1a\xb3\x01\n\x05Query\x1a\x17\n\x04List\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x1a(\n\x03Get\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08\x61larm_id\x18\x02 \x01(\t\x1a:\n\x06\x43reate\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x1f\n\x05\x61larm\x18\x02 \x01(\x0b\x32\x10.aif.kaist.Alarm\x1a+\n\x06\x44\x65lete\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08\x61larm_id\x18\x02 \x01(\t2\x9c\x02\n\x14\x41larmScheduleService\x12>\n\tListAlarm\x12\x1b.aif.kaist.Alarm.Query.List\x1a\x10.aif.kaist.Alarm\"\x00\x30\x01\x12:\n\x08GetAlarm\x12\x1a.aif.kaist.Alarm.Query.Get\x1a\x10.aif.kaist.Alarm\"\x00\x12@\n\x0b\x43reateAlarm\x12\x1d.aif.kaist.Alarm.Query.Create\x1a\x10.aif.kaist.Alarm\"\x00\x12\x46\n\x0b\x44\x65leteAlarm\x12\x1d.aif.kaist.Alarm.Query.Delete\x1a\x16.google.protobuf.Empty\"\x00\x32R\n\x14\x41larmReceiverService\x12:\n\x0cReceiveAlarm\x12\x10.aif.kaist.Alarm\x1a\x16.google.protobuf.Empty\"\x00\x42%\n\x16\x61if.kaist.iclab.protosB\x0b\x41larmProtosb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ALARM_QUERY_LIST = _descriptor.Descriptor(
  name='List',
  full_name='aif.kaist.Alarm.Query.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='aif.kaist.Alarm.Query.List.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=244,
)

_ALARM_QUERY_GET = _descriptor.Descriptor(
  name='Get',
  full_name='aif.kaist.Alarm.Query.Get',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='aif.kaist.Alarm.Query.Get.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm_id', full_name='aif.kaist.Alarm.Query.Get.alarm_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=286,
)

_ALARM_QUERY_CREATE = _descriptor.Descriptor(
  name='Create',
  full_name='aif.kaist.Alarm.Query.Create',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='aif.kaist.Alarm.Query.Create.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm', full_name='aif.kaist.Alarm.Query.Create.alarm', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=346,
)

_ALARM_QUERY_DELETE = _descriptor.Descriptor(
  name='Delete',
  full_name='aif.kaist.Alarm.Query.Delete',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='aif.kaist.Alarm.Query.Delete.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm_id', full_name='aif.kaist.Alarm.Query.Delete.alarm_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=391,
)

_ALARM_QUERY = _descriptor.Descriptor(
  name='Query',
  full_name='aif.kaist.Alarm.Query',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_ALARM_QUERY_LIST, _ALARM_QUERY_GET, _ALARM_QUERY_CREATE, _ALARM_QUERY_DELETE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=391,
)

_ALARM = _descriptor.Descriptor(
  name='Alarm',
  full_name='aif.kaist.Alarm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='aif.kaist.Alarm.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='alarm_id', full_name='aif.kaist.Alarm.alarm_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='aif.kaist.Alarm.destination', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='delay_millis', full_name='aif.kaist.Alarm.delay_millis', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='interval_millis', full_name='aif.kaist.Alarm.interval_millis', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scheduled_millis', full_name='aif.kaist.Alarm.scheduled_millis', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='aif.kaist.Alarm.content', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ALARM_QUERY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=391,
)

_ALARM_QUERY_LIST.containing_type = _ALARM_QUERY
_ALARM_QUERY_GET.containing_type = _ALARM_QUERY
_ALARM_QUERY_CREATE.fields_by_name['alarm'].message_type = _ALARM
_ALARM_QUERY_CREATE.containing_type = _ALARM_QUERY
_ALARM_QUERY_DELETE.containing_type = _ALARM_QUERY
_ALARM_QUERY.containing_type = _ALARM
DESCRIPTOR.message_types_by_name['Alarm'] = _ALARM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Alarm = _reflection.GeneratedProtocolMessageType('Alarm', (_message.Message,), dict(

  Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), dict(

    List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), dict(
      DESCRIPTOR = _ALARM_QUERY_LIST,
      __module__ = 'alarm_pb2'
      # @@protoc_insertion_point(class_scope:aif.kaist.Alarm.Query.List)
      ))
    ,

    Get = _reflection.GeneratedProtocolMessageType('Get', (_message.Message,), dict(
      DESCRIPTOR = _ALARM_QUERY_GET,
      __module__ = 'alarm_pb2'
      # @@protoc_insertion_point(class_scope:aif.kaist.Alarm.Query.Get)
      ))
    ,

    Create = _reflection.GeneratedProtocolMessageType('Create', (_message.Message,), dict(
      DESCRIPTOR = _ALARM_QUERY_CREATE,
      __module__ = 'alarm_pb2'
      # @@protoc_insertion_point(class_scope:aif.kaist.Alarm.Query.Create)
      ))
    ,

    Delete = _reflection.GeneratedProtocolMessageType('Delete', (_message.Message,), dict(
      DESCRIPTOR = _ALARM_QUERY_DELETE,
      __module__ = 'alarm_pb2'
      # @@protoc_insertion_point(class_scope:aif.kaist.Alarm.Query.Delete)
      ))
    ,
    DESCRIPTOR = _ALARM_QUERY,
    __module__ = 'alarm_pb2'
    # @@protoc_insertion_point(class_scope:aif.kaist.Alarm.Query)
    ))
  ,
  DESCRIPTOR = _ALARM,
  __module__ = 'alarm_pb2'
  # @@protoc_insertion_point(class_scope:aif.kaist.Alarm)
  ))
_sym_db.RegisterMessage(Alarm)
_sym_db.RegisterMessage(Alarm.Query)
_sym_db.RegisterMessage(Alarm.Query.List)
_sym_db.RegisterMessage(Alarm.Query.Get)
_sym_db.RegisterMessage(Alarm.Query.Create)
_sym_db.RegisterMessage(Alarm.Query.Delete)


DESCRIPTOR._options = None

_ALARMSCHEDULESERVICE = _descriptor.ServiceDescriptor(
  name='AlarmScheduleService',
  full_name='aif.kaist.AlarmScheduleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=394,
  serialized_end=678,
  methods=[
  _descriptor.MethodDescriptor(
    name='ListAlarm',
    full_name='aif.kaist.AlarmScheduleService.ListAlarm',
    index=0,
    containing_service=None,
    input_type=_ALARM_QUERY_LIST,
    output_type=_ALARM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAlarm',
    full_name='aif.kaist.AlarmScheduleService.GetAlarm',
    index=1,
    containing_service=None,
    input_type=_ALARM_QUERY_GET,
    output_type=_ALARM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreateAlarm',
    full_name='aif.kaist.AlarmScheduleService.CreateAlarm',
    index=2,
    containing_service=None,
    input_type=_ALARM_QUERY_CREATE,
    output_type=_ALARM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteAlarm',
    full_name='aif.kaist.AlarmScheduleService.DeleteAlarm',
    index=3,
    containing_service=None,
    input_type=_ALARM_QUERY_DELETE,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALARMSCHEDULESERVICE)

DESCRIPTOR.services_by_name['AlarmScheduleService'] = _ALARMSCHEDULESERVICE


_ALARMRECEIVERSERVICE = _descriptor.ServiceDescriptor(
  name='AlarmReceiverService',
  full_name='aif.kaist.AlarmReceiverService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=680,
  serialized_end=762,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReceiveAlarm',
    full_name='aif.kaist.AlarmReceiverService.ReceiveAlarm',
    index=0,
    containing_service=None,
    input_type=_ALARM,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALARMRECEIVERSERVICE)

DESCRIPTOR.services_by_name['AlarmReceiverService'] = _ALARMRECEIVERSERVICE

# @@protoc_insertion_point(module_scope)
