# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import alarm_pb2 as alarm__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AlarmScheduleServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ListAlarm = channel.unary_stream(
        '/aif.kaist.AlarmScheduleService/ListAlarm',
        request_serializer=alarm__pb2.Alarm.Query.List.SerializeToString,
        response_deserializer=alarm__pb2.Alarm.FromString,
        )
    self.GetAlarm = channel.unary_unary(
        '/aif.kaist.AlarmScheduleService/GetAlarm',
        request_serializer=alarm__pb2.Alarm.Query.Get.SerializeToString,
        response_deserializer=alarm__pb2.Alarm.FromString,
        )
    self.CreateAlarm = channel.unary_unary(
        '/aif.kaist.AlarmScheduleService/CreateAlarm',
        request_serializer=alarm__pb2.Alarm.Query.Create.SerializeToString,
        response_deserializer=alarm__pb2.Alarm.FromString,
        )
    self.DeleteAlarm = channel.unary_unary(
        '/aif.kaist.AlarmScheduleService/DeleteAlarm',
        request_serializer=alarm__pb2.Alarm.Query.Delete.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class AlarmScheduleServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ListAlarm(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAlarm(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateAlarm(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteAlarm(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AlarmScheduleServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ListAlarm': grpc.unary_stream_rpc_method_handler(
          servicer.ListAlarm,
          request_deserializer=alarm__pb2.Alarm.Query.List.FromString,
          response_serializer=alarm__pb2.Alarm.SerializeToString,
      ),
      'GetAlarm': grpc.unary_unary_rpc_method_handler(
          servicer.GetAlarm,
          request_deserializer=alarm__pb2.Alarm.Query.Get.FromString,
          response_serializer=alarm__pb2.Alarm.SerializeToString,
      ),
      'CreateAlarm': grpc.unary_unary_rpc_method_handler(
          servicer.CreateAlarm,
          request_deserializer=alarm__pb2.Alarm.Query.Create.FromString,
          response_serializer=alarm__pb2.Alarm.SerializeToString,
      ),
      'DeleteAlarm': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteAlarm,
          request_deserializer=alarm__pb2.Alarm.Query.Delete.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'aif.kaist.AlarmScheduleService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class AlarmReceiverServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReceiveAlarm = channel.unary_unary(
        '/aif.kaist.AlarmReceiverService/ReceiveAlarm',
        request_serializer=alarm__pb2.Alarm.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class AlarmReceiverServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ReceiveAlarm(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AlarmReceiverServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReceiveAlarm': grpc.unary_unary_rpc_method_handler(
          servicer.ReceiveAlarm,
          request_deserializer=alarm__pb2.Alarm.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'aif.kaist.AlarmReceiverService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
